/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula;


import javax.swing.JOptionPane;


/**
 *
 * @author 0040481722014
 */
public class CalculadoraJFrame extends javax.swing.JFrame {

    double num1, num2, resultado;
    char operacao;
    
    
    /**
     * Creates new form CalculadoraJFrame
     */
    public CalculadoraJFrame() {
        initComponents();
        
       jPanel1.setFocusable(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resultadoTextField = new javax.swing.JTextField();
        oneButton = new javax.swing.JButton();
        operationSomaButton = new javax.swing.JButton();
        operationIngualButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        operationMenosButton = new javax.swing.JButton();
        operationMultButton1 = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        operationDiviButton2 = new javax.swing.JButton();
        pontoButton = new javax.swing.JButton();
        deleteButton3 = new javax.swing.JButton();
        operationPorcButton = new javax.swing.JButton();
        backspaceButton4 = new javax.swing.JButton();
        lbTempTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aula 1 - Calculadora");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        resultadoTextField.setEditable(false);
        resultadoTextField.setFont(new java.awt.Font("Quartz MS", 0, 36)); // NOI18N
        resultadoTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultadoTextField.setText("0");
        resultadoTextField.setToolTipText("Resultado");
        resultadoTextField.setBorder(null);
        resultadoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoTextFieldActionPerformed(evt);
            }
        });

        oneButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        oneButton.setText("1");
        oneButton.setToolTipText("");
        oneButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        oneButton.setMaximumSize(new java.awt.Dimension(64, 64));
        oneButton.setMinimumSize(new java.awt.Dimension(64, 64));
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        operationSomaButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        operationSomaButton.setText("+");
        operationSomaButton.setToolTipText("");
        operationSomaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        operationSomaButton.setMaximumSize(new java.awt.Dimension(64, 64));
        operationSomaButton.setMinimumSize(new java.awt.Dimension(64, 64));
        operationSomaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationSomaButtonActionPerformed(evt);
            }
        });

        operationIngualButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        operationIngualButton.setText("=");
        operationIngualButton.setToolTipText("");
        operationIngualButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        operationIngualButton.setMaximumSize(new java.awt.Dimension(64, 64));
        operationIngualButton.setMinimumSize(new java.awt.Dimension(64, 64));
        operationIngualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationIngualButtonActionPerformed(evt);
            }
        });

        twoButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        twoButton.setText("2");
        twoButton.setToolTipText("");
        twoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        twoButton.setMaximumSize(new java.awt.Dimension(64, 64));
        twoButton.setMinimumSize(new java.awt.Dimension(64, 64));
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        threeButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        threeButton.setText("3");
        threeButton.setToolTipText("");
        threeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        threeButton.setMaximumSize(new java.awt.Dimension(64, 64));
        threeButton.setMinimumSize(new java.awt.Dimension(64, 64));
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        fourButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        fourButton.setText("4");
        fourButton.setToolTipText("");
        fourButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fourButton.setMaximumSize(new java.awt.Dimension(64, 64));
        fourButton.setMinimumSize(new java.awt.Dimension(64, 64));
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        fiveButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        fiveButton.setText("5");
        fiveButton.setToolTipText("");
        fiveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fiveButton.setMaximumSize(new java.awt.Dimension(64, 64));
        fiveButton.setMinimumSize(new java.awt.Dimension(64, 64));
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        sixButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        sixButton.setText("6");
        sixButton.setToolTipText("");
        sixButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sixButton.setMaximumSize(new java.awt.Dimension(64, 64));
        sixButton.setMinimumSize(new java.awt.Dimension(64, 64));
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        sevenButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        sevenButton.setText("7");
        sevenButton.setToolTipText("");
        sevenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sevenButton.setMaximumSize(new java.awt.Dimension(64, 64));
        sevenButton.setMinimumSize(new java.awt.Dimension(64, 64));
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        eightButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        eightButton.setText("8");
        eightButton.setToolTipText("");
        eightButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eightButton.setMaximumSize(new java.awt.Dimension(64, 64));
        eightButton.setMinimumSize(new java.awt.Dimension(64, 64));
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        nineButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        nineButton.setText("9");
        nineButton.setToolTipText("");
        nineButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nineButton.setMaximumSize(new java.awt.Dimension(64, 64));
        nineButton.setMinimumSize(new java.awt.Dimension(64, 64));
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        operationMenosButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        operationMenosButton.setText("-");
        operationMenosButton.setToolTipText("");
        operationMenosButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        operationMenosButton.setMaximumSize(new java.awt.Dimension(64, 64));
        operationMenosButton.setMinimumSize(new java.awt.Dimension(64, 64));
        operationMenosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationMenosButtonActionPerformed(evt);
            }
        });

        operationMultButton1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        operationMultButton1.setText("x");
        operationMultButton1.setToolTipText("");
        operationMultButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        operationMultButton1.setMaximumSize(new java.awt.Dimension(64, 64));
        operationMultButton1.setMinimumSize(new java.awt.Dimension(64, 64));
        operationMultButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationMultButton1ActionPerformed(evt);
            }
        });

        zeroButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        zeroButton.setText("0");
        zeroButton.setToolTipText("");
        zeroButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zeroButton.setMaximumSize(new java.awt.Dimension(64, 64));
        zeroButton.setMinimumSize(new java.awt.Dimension(64, 64));
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        operationDiviButton2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        operationDiviButton2.setText("/");
        operationDiviButton2.setToolTipText("");
        operationDiviButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        operationDiviButton2.setMaximumSize(new java.awt.Dimension(64, 64));
        operationDiviButton2.setMinimumSize(new java.awt.Dimension(64, 64));
        operationDiviButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationDiviButton2ActionPerformed(evt);
            }
        });

        pontoButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        pontoButton.setText(".");
        pontoButton.setToolTipText("");
        pontoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pontoButton.setMaximumSize(new java.awt.Dimension(64, 64));
        pontoButton.setMinimumSize(new java.awt.Dimension(64, 64));
        pontoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontoButtonActionPerformed(evt);
            }
        });

        deleteButton3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        deleteButton3.setText("C");
        deleteButton3.setToolTipText("");
        deleteButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton3.setMaximumSize(new java.awt.Dimension(64, 64));
        deleteButton3.setMinimumSize(new java.awt.Dimension(64, 64));
        deleteButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton3ActionPerformed(evt);
            }
        });

        operationPorcButton.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        operationPorcButton.setText("√");
        operationPorcButton.setToolTipText("");
        operationPorcButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        operationPorcButton.setMaximumSize(new java.awt.Dimension(64, 64));
        operationPorcButton.setMinimumSize(new java.awt.Dimension(64, 64));
        operationPorcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationPorcButtonActionPerformed(evt);
            }
        });

        backspaceButton4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        backspaceButton4.setText("CE");
        backspaceButton4.setToolTipText("");
        backspaceButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backspaceButton4.setMaximumSize(new java.awt.Dimension(64, 64));
        backspaceButton4.setMinimumSize(new java.awt.Dimension(64, 64));
        backspaceButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceButton4ActionPerformed(evt);
            }
        });

        lbTempTextField.setEditable(false);
        lbTempTextField.setBackground(new java.awt.Color(153, 153, 153));
        lbTempTextField.setFont(new java.awt.Font("Quartz MS", 0, 18)); // NOI18N
        lbTempTextField.setForeground(new java.awt.Color(204, 204, 204));
        lbTempTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lbTempTextField.setToolTipText("Resultado");
        lbTempTextField.setBorder(null);
        lbTempTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTempTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(operationPorcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(oneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sevenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fourButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(eightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pontoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sixButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(backspaceButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(operationDiviButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(operationIngualButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(operationMenosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(operationSomaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(operationMultButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbTempTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultadoTextField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(lbTempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operationMultButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operationDiviButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backspaceButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operationSomaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(operationMenosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(operationPorcButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pontoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(operationIngualButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        /*String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "1");*/
        setarNumerosNoResultadoTxV('1');
        
    }//GEN-LAST:event_oneButtonActionPerformed

    private void resultadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoTextFieldActionPerformed

    private void operationSomaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationSomaButtonActionPerformed

      /*  textoA = resultadoTextField.getText();
        resultadoTextField.setText("");
        operacao = "+";*/
      
     pegarNum1();
     
     operacao= '+';
     setarvalorlbtemp();
     
    }//GEN-LAST:event_operationSomaButtonActionPerformed

    private void operationIngualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationIngualButtonActionPerformed

       /* textoB = resultadoTextField.getText();
        resultadoTextField.setText("");

        double a = Integer.parseInt(textoA);
        double b = Integer.parseInt(textoB);
        double total = 0.000;

        switch (operacao) {
            case "+":
                total = a + b;
                break;
            case "-":
                total = a - b;
                break;
            case "*":
                total = a * b;
                break;
            case "/":
                total = a / b;
                break;
            case "%":
                total = a / 100;
               break;
        }

        String numero = String.valueOf(total);
        resultadoTextField.setText(numero);*/

       pegarNum2();
       calcular();
       
       lbTempTextField.setText("");
       
       
    }//GEN-LAST:event_operationIngualButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
       /* String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "2");*/
       
        setarNumerosNoResultadoTxV('2');
    }//GEN-LAST:event_twoButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        /* String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "3");*/
        
        setarNumerosNoResultadoTxV('3');
    }//GEN-LAST:event_threeButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        /*String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "4");*/
        
        setarNumerosNoResultadoTxV('4');
    }//GEN-LAST:event_fourButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        /*String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "5");*/
        
        setarNumerosNoResultadoTxV('5');
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        /*String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "6");*/
        
        setarNumerosNoResultadoTxV('6');
    }//GEN-LAST:event_sixButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        /*String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "7");*/
        
        setarNumerosNoResultadoTxV('7');
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        /*String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "8");*/
        
        setarNumerosNoResultadoTxV('8');
    }//GEN-LAST:event_eightButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        /*String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "9");*/
        
        setarNumerosNoResultadoTxV('9');
    }//GEN-LAST:event_nineButtonActionPerformed

    private void operationMenosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationMenosButtonActionPerformed
        /*textoA = resultadoTextField.getText();
        resultadoTextField.setText("");
        operacao = "-";*/
        
        pegarNum1();
        
        operacao='-';
        setarvalorlbtemp();
    }//GEN-LAST:event_operationMenosButtonActionPerformed

    private void operationMultButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationMultButton1ActionPerformed
        /*textoA = resultadoTextField.getText();
        resultadoTextField.setText("");
        operacao = "*";*/
        
        pegarNum1();
        
        operacao='*';
        setarvalorlbtemp();
    }//GEN-LAST:event_operationMultButton1ActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        /*String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "0");*/
        
        setarNumerosNoResultadoTxV('0');
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void operationDiviButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationDiviButton2ActionPerformed
       /* textoA = resultadoTextField.getText();
        resultadoTextField.setText("");
        operacao = "/";*/
     
       pegarNum1();
       
       operacao='/';
       setarvalorlbtemp();
    }//GEN-LAST:event_operationDiviButton2ActionPerformed

    private void pontoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontoButtonActionPerformed
       /* //String entrada = "12,345";
        //double valor = Double.parseDouble(entrada.replace(',', '.'));
        String total = resultadoTextField.getText();
        resultadoTextField.setText(resultadoTextField.getText() +".");
        Double valor = new Double(resultadoTextField.getText());*/
       
       setarNumerosNoResultadoTxV('.');
    }//GEN-LAST:event_pontoButtonActionPerformed

    private void deleteButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton3ActionPerformed
        num1=0;
        num2=0;
        resultado=0;
        resultadoTextField.setText("0");    
        lbTempTextField.setText("");
        jPanel1.requestFocus();
    }//GEN-LAST:event_deleteButton3ActionPerformed

    private void operationPorcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationPorcButtonActionPerformed
        
        /*textoA=resultadoTextField.getText();
        resultadoTextField.setText("");
        operacao = "%";
        
        double total = 0.00;
        
        String numero = String.valueOf(total);
        resultadoTextField.setText(numero);*/
        
        pegarNum1();
        
        operacao='√';
        calcular();
        
        setarvalorlbtemp();
    }//GEN-LAST:event_operationPorcButtonActionPerformed

    private void backspaceButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceButton4ActionPerformed
        String valor_resultadotextfield = resultadoTextField.getText();
        
        if(valor_resultadotextfield.length() > 0){
            if(".".equals(valor_resultadotextfield.substring(valor_resultadotextfield.length()-2, valor_resultadotextfield.length()-1)) ){
          valor_resultadotextfield = valor_resultadotextfield.substring(0, valor_resultadotextfield.length()-2);  
            
        }else{
            valor_resultadotextfield = valor_resultadotextfield.substring(0, valor_resultadotextfield.length()-1);
        }
        
            resultadoTextField.setText(valor_resultadotextfield);
        
        
        if (valor_resultadotextfield.length() == 0){
            resultadoTextField.setText("0");
        }
        
        }else{
            resultadoTextField.setText("0");
        }
        
        jPanel1.requestFocus();
    }//GEN-LAST:event_backspaceButton4ActionPerformed

    private void lbTempTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTempTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTempTextFieldActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        if(evt.getKeyChar() == '0' ||
                evt.getKeyChar() == '1' ||
                evt.getKeyChar() == '2' ||
                evt.getKeyChar() == '3' ||
                evt.getKeyChar() == '4' ||
                evt.getKeyChar() == '5' ||
                evt.getKeyChar() == '6' ||
                evt.getKeyChar() == '7' ||
                evt.getKeyChar() == '8' || 
                evt.getKeyChar() == '9' ||  
                evt.getKeyChar() == '.' ){
            setarNumerosNoResultadoTxV(evt.getKeyChar());
        }else if(evt.getKeyChar() == '-' ||
                evt.getKeyChar() == '+' ||
                evt.getKeyChar() == '*' ||
                evt.getKeyChar() == '/'){
            
            pegarNum1();
            operacao= evt.getKeyChar();
            setarvalorlbtemp();
        }else if(evt.getKeyCode()==10){
            pegarNum2();
            calcular();
            lbTempTextField.setText("");
        }else if(evt.getKeyCode()==8){
            resumocodbackspace();
        }
        //System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_jPanel1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraJFrame().setVisible(true);
            }
        });
    }
    
    
    private String textoA;
    private String textoB;
    //private String operacao;
    private String valor;
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backspaceButton4;
    private javax.swing.JButton deleteButton3;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lbTempTextField;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton operationDiviButton2;
    private javax.swing.JButton operationIngualButton;
    private javax.swing.JButton operationMenosButton;
    private javax.swing.JButton operationMultButton1;
    private javax.swing.JButton operationPorcButton;
    private javax.swing.JButton operationSomaButton;
    private javax.swing.JButton pontoButton;
    private javax.swing.JTextField resultadoTextField;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables


public void setarNumerosNoResultadoTxV (char numero){
    
    if("0".equals(resultadoTextField.getText()) && !".".equals(String.valueOf(numero))){
        resultadoTextField.setText("");   
    }
    
    String texto = resultadoTextField.getText();
    
    if(texto.length() <= 14){
    texto = texto+numero;
    resultadoTextField.setText(texto);
    
    jPanel1.requestFocus();
    }
}

public void pegarNum1(){
    num1 = Double.parseDouble(resultadoTextField.getText());
    resultadoTextField.setText("0");
    jPanel1.requestFocus();
}


public void pegarNum2(){
    
    num2 = Double.parseDouble(resultadoTextField.getText());
    resultadoTextField.setText("0");
}

public void calcular(){
    
    
    if (num2 == 0 && operacao == '/'){
        JOptionPane.showMessageDialog(null,"Operação invalida!"); 
        reiniciarcalculadora();
    }else {
     if (operacao == '+'){
        resultado = num1+num2;
    }else if (operacao == '/'){
        resultado = num1/num2;
    }else if (operacao == '*'){
        resultado = num1*num2;
    }else if (operacao == '-'){
        resultado = num1-num2;
    }else {
        resultado = Math.sqrt(num1);
    }
     
    resultadoTextField.setText(String.valueOf(resultado));
    }
    jPanel1.requestFocus();
    
    
    
}

public void setarvalorlbtemp (){
    
    lbTempTextField.setText(String.valueOf(num1)+" "+ operacao);
    
}


public void reiniciarcalculadora(){
    num1=0;
    num2=0;
    resultado=0;
    resultadoTextField.setText("0"); 
}

public void resumocodbackspace(){
    String valor_resultadotextfield = resultadoTextField.getText();
        
        if(valor_resultadotextfield.length() > 0){
            if(".".equals(valor_resultadotextfield.substring(valor_resultadotextfield.length()-2, valor_resultadotextfield.length()-1)) ){
          valor_resultadotextfield = valor_resultadotextfield.substring(0, valor_resultadotextfield.length()-2);  
            
        }else{
            valor_resultadotextfield = valor_resultadotextfield.substring(0, valor_resultadotextfield.length()-1);
        }
        
            resultadoTextField.setText(valor_resultadotextfield);
        
        
        if (valor_resultadotextfield.length() == 0){
            resultadoTextField.setText("0");
        }
        
        }else{
            resultadoTextField.setText("0");
        }
        
        jPanel1.requestFocus();
}

}